/* =========================================================
   ¡Vamos! · 스페인어 학습 데이터 (Day 1 ~ Day 32)
   ---------------------------------------------------------
   📝 사용법:
   - 새 단어/표현 추가: 해당 Day의 cards 배열에 { es, ko } 추가
   - 새 Day 주제 추가: TOPICS 배열에 새 객체 추가
       { id: 'day33', emoji: '🎉', title: 'Day 33 · ...',
         subtitle: '¿Qué hago ...?',
         cards: [ { es: '...', ko: '...' }, ... ] }
   - 카드 수정/삭제: 해당 항목을 그냥 편집하거나 지우면 됨
   - 저장 후 브라우저에서 새로고침(F5)만 하면 즉시 반영됩니다.

   필드 설명:
   - id        : 고유 식별자 (영문 소문자/숫자만)
   - emoji     : 주제 칩에 표시될 이모지
   - title     : 주제 이름 (UI에 큰 글씨로 표시)
   - subtitle  : 부제 (보통 스페인어 질문 형식)
   - cards     : 학습할 카드 배열
       - es : 스페인어 (앞면)
       - ko : 한국어 뜻 (뒷면)
   ========================================================= */

const TOPICS = [
  {
    id: 'day1', emoji: '🏢',
    title: 'Day 1 · 사무실',
    subtitle: '¿Qué hago en mi oficina?',
    cards: [
      { es: 'la oficina', ko: '사무실' },
      { es: 'el documento', ko: '문서' },
      { es: 'el informe', ko: '보고서' },
      { es: 'la solicitud', ko: '신청서' },
      { es: 'el formulario', ko: '양식, 서식' },
      { es: 'preparar', ko: '준비하다' },
      { es: 'imprimir', ko: '인쇄하다' },
      { es: 'firmar', ko: '서명하다' },
      { es: 'revisar', ko: '검토하다' },
      { es: 'enviar', ko: '보내다' },
      { es: 'archivar', ko: '문서를 보관하다, 철하다' },
      { es: 'rellenar', ko: '(양식을) 작성하다' },
      { es: 'Tengo que preparar el documento.', ko: '나는 문서를 준비해야 한다.' },
      { es: 'Estoy imprimiendo un informe.', ko: '나는 보고서를 인쇄하고 있다.' },
      { es: 'Voy a enviar el documento.', ko: '나는 문서를 보낼 것이다.' },
      { es: 'Puedo rellenar el formulario.', ko: '나는 양식을 작성할 수 있다.' },
    ],
  },
  {
    id: 'day2', emoji: '☕',
    title: 'Day 2 · 카페',
    subtitle: '¿Qué hago en la cafetería?',
    cards: [
      { es: 'la cafetería', ko: '카페' },
      { es: 'el café con leche', ko: '카페라떼' },
      { es: 'el té', ko: '차' },
      { es: 'el zumo', ko: '주스' },
      { es: 'la tarta', ko: '케이크, 타르트' },
      { es: 'la carta', ko: '메뉴판' },
      { es: 'la cuenta', ko: '계산서' },
      { es: 'la terraza', ko: '테라스' },
      { es: 'pedir un café', ko: '커피를 주문하다' },
      { es: 'elegir de la carta', ko: '메뉴판에서 고르다' },
      { es: 'tomar algo', ko: '뭔가를 마시다' },
      { es: 'sentarse en la terraza', ko: '테라스에 앉다' },
      { es: 'pagar la cuenta', ko: '계산하다' },
      { es: 'Voy a pedir un café con leche.', ko: '나는 카페라떼를 주문할 것이다.' },
      { es: 'Quiero sentarme cerca de la ventana.', ko: '나는 창가에 앉고 싶다.' },
      { es: '¿Me trae la carta, por favor?', ko: '메뉴판 좀 가져다주시겠어요?' },
    ],
  },
  {
    id: 'day3', emoji: '🌳',
    title: 'Day 3 · 공원',
    subtitle: '¿Qué hago en el parque?',
    cards: [
      { es: 'el parque', ko: '공원' },
      { es: 'el sendero', ko: '산책로, 오솔길' },
      { es: 'el perro', ko: '개' },
      { es: 'el picnic', ko: '피크닉' },
      { es: 'el aire libre', ko: '야외, 바깥 공기' },
      { es: 'caminar por el sendero', ko: '산책로를 따라 걷다' },
      { es: 'pasear al perro', ko: '개를 산책시키다' },
      { es: 'escuchar música', ko: '음악을 듣다' },
      { es: 'hacer ejercicio', ko: '운동하다' },
      { es: 'comer al aire libre', ko: '야외에서 먹다' },
      { es: 'hacer un picnic', ko: '피크닉을 하다' },
      { es: 'tomar una selfie', ko: '셀카를 찍다' },
      { es: 'andar', ko: '걷다' },
      { es: 'Voy a caminar por el sendero del parque.', ko: '나는 공원 산책로를 따라 걸을 것이다.' },
      { es: 'Tengo que pasear al perro en el parque.', ko: '나는 공원에서 개를 산책시켜야 한다.' },
      { es: 'Quiero hacer un picnic en el parque.', ko: '나는 공원에서 피크닉을 하고 싶다.' },
    ],
  },
  {
    id: 'day4', emoji: '📚',
    title: 'Day 4 · 도서관',
    subtitle: '¿Qué hago en la biblioteca?',
    cards: [
      { es: 'la biblioteca', ko: '도서관' },
      { es: 'el libro', ko: '책' },
      { es: 'el estante', ko: '책장, 서가' },
      { es: 'el carné', ko: '회원증, 카드' },
      { es: 'la sala de lectura', ko: '열람실' },
      { es: 'el silencio', ko: '정숙, 조용함' },
      { es: 'buscar un libro', ko: '책을 찾다' },
      { es: 'pedir prestado un libro', ko: '책을 대출하다' },
      { es: 'devolver el libro', ko: '책을 반납하다' },
      { es: 'leer en silencio', ko: '조용히 읽다' },
      { es: 'estudiar', ko: '공부하다' },
      { es: 'tomar apuntes', ko: '필기하다' },
      { es: 'guardar silencio', ko: '정숙을 지키다' },
      { es: 'Tengo que devolver el libro hoy.', ko: '나는 오늘 책을 반납해야 한다.' },
      { es: 'Voy a estudiar en la sala de lectura.', ko: '나는 열람실에서 공부할 것이다.' },
      { es: 'Hay que guardar silencio en la biblioteca.', ko: '도서관에서는 정숙해야 한다.' },
    ],
  },
  {
    id: 'day5', emoji: '🏋️',
    title: 'Day 5 · 헬스장',
    subtitle: '¿Qué hago en el gimnasio?',
    cards: [
      { es: 'la mochila', ko: '가방' },
      { es: 'las pesas', ko: '덤벨, 웨이트' },
      { es: 'la bicicleta estática', ko: '실내 자전거' },
      { es: 'la cinta', ko: '러닝머신' },
      { es: 'la ropa deportiva', ko: '운동복' },
      { es: 'la ducha', ko: '샤워, 샤워실' },
      { es: 'levantar pesas', ko: '덤벨을 들다' },
      { es: 'correr en la cinta', ko: '러닝머신에서 달리다' },
      { es: 'estirar el cuerpo', ko: '스트레칭하다' },
      { es: 'ducharse', ko: '샤워하다' },
      { es: 'Me gusta entrenar con pesas.', ko: '나는 웨이트 운동을 좋아한다.' },
    ],
  },
  {
    id: 'day6', emoji: '💻',
    title: 'Day 6 · 컴퓨터/사무',
    subtitle: '¿Qué hago con mi computadora?',
    cards: [
      { es: 'la computadora', ko: '컴퓨터' },
      { es: 'el correo electrónico', ko: '이메일' },
      { es: 'el documento', ko: '문서' },
      { es: 'el archivo', ko: '파일' },
      { es: 'encender / apagar', ko: '켜다 / 끄다' },
      { es: 'guardar', ko: '저장하다' },
      { es: 'enviar', ko: '보내다' },
      { es: 'adjuntar', ko: '첨부하다' },
      { es: 'descargar', ko: '다운로드하다' },
      { es: 'responder el correo', ko: '이메일에 답장하다' },
      { es: 'navegar por internet', ko: '인터넷을 검색하다' },
    ],
  },
  {
    id: 'day7', emoji: '🥕',
    title: 'Day 7 · 채소 손질',
    subtitle: '¿Qué hago con las verduras? 1',
    cards: [
      { es: 'la verdura', ko: '채소' },
      { es: 'la cebolla', ko: '양파' },
      { es: 'la zanahoria', ko: '당근' },
      { es: 'la patata', ko: '감자' },
      { es: 'la lechuga', ko: '상추' },
      { es: 'lavar', ko: '씻다' },
      { es: 'pelar', ko: '껍질을 벗기다' },
      { es: 'cortar', ko: '자르다' },
      { es: 'picar', ko: '잘게 다지다' },
      { es: 'cortar en tiras', ko: '채썰다' },
      { es: 'guardar en la nevera', ko: '냉장고에 넣다' },
    ],
  },
  {
    id: 'day8', emoji: '🍳',
    title: 'Day 8 · 주방/요리',
    subtitle: '¿Qué hago con las verduras? 2',
    cards: [
      { es: 'la sartén', ko: '후라이팬' },
      { es: 'la olla', ko: '냄비' },
      { es: 'el horno', ko: '오븐' },
      { es: 'la sal', ko: '소금' },
      { es: 'el aceite', ko: '기름' },
      { es: 'freír', ko: '튀기다, 볶다' },
      { es: 'saltear', ko: '살짝 볶다' },
      { es: 'hervir', ko: '삶다, 끓이다' },
      { es: 'hornear', ko: '오븐에 굽다' },
      { es: 'mezclar', ko: '섞다' },
      { es: 'Empiezo a cocinar.', ko: '나는 요리를 시작한다.' },
    ],
  },
  {
    id: 'day9', emoji: '🎒',
    title: 'Day 9 · 소지품 (일상)',
    subtitle: '¿Qué tengo en mi bolso?',
    cards: [
      { es: 'el bolso', ko: '가방' },
      { es: 'las llaves', ko: '열쇠' },
      { es: 'el móvil', ko: '휴대폰' },
      { es: 'la cartera', ko: '지갑' },
      { es: 'los auriculares', ko: '이어폰' },
      { es: 'el paraguas', ko: '우산' },
      { es: 'el libro', ko: '책' },
      { es: 'las gafas', ko: '안경' },
      { es: 'la botella', ko: '물병' },
      { es: 'el pañuelo', ko: '손수건' },
      { es: 'el bolígrafo', ko: '볼펜' },
      { es: 'el espejo', ko: '거울' },
    ],
  },
  {
    id: 'day10', emoji: '👜',
    title: 'Day 10 · 소지품 (여행)',
    subtitle: '¿Qué llevo en mi maleta?',
    cards: [
      { es: 'el pasaporte', ko: '여권' },
      { es: 'el DNI', ko: '신분증' },
      { es: 'el efectivo', ko: '현금' },
      { es: 'la tarjeta de crédito', ko: '신용카드' },
      { es: 'la tarjeta de embarque', ko: '탑승권' },
      { es: 'el mapa', ko: '지도' },
      { es: 'la guía', ko: '가이드북' },
      { es: 'el cargador', ko: '충전기' },
      { es: 'la maleta', ko: '캐리어' },
      { es: 'el billete', ko: '티켓, 표' },
      { es: 'la cámara', ko: '카메라' },
      { es: 'el seguro de viaje', ko: '여행자 보험' },
    ],
  },
  {
    id: 'day11', emoji: '✈️',
    title: 'Day 11 · 공항',
    subtitle: '¿Qué hago en el aeropuerto?',
    cards: [
      { es: 'el aeropuerto', ko: '공항' },
      { es: 'el vuelo', ko: '비행' },
      { es: 'el equipaje', ko: '수하물, 짐' },
      { es: 'la puerta de embarque', ko: '탑승구' },
      { es: 'facturar el equipaje', ko: '수하물을 부치다' },
      { es: 'embarcar', ko: '탑승하다' },
      { es: 'recoger el equipaje', ko: '수하물을 찾다' },
      { es: 'hacer cola', ko: '줄을 서다' },
      { es: 'pasar el control', ko: '보안 검색을 통과하다' },
      { es: 'aterrizar', ko: '착륙하다' },
      { es: 'despegar', ko: '이륙하다' },
    ],
  },
  {
    id: 'day12', emoji: '🏖️',
    title: 'Day 12 · 해변',
    subtitle: '¿Qué hago en la playa?',
    cards: [
      { es: 'la playa', ko: '해변' },
      { es: 'el mar', ko: '바다' },
      { es: 'el sol', ko: '태양' },
      { es: 'la arena', ko: '모래' },
      { es: 'nadar en la playa', ko: '해변에서 수영하다' },
      { es: 'tomar el sol', ko: '일광욕하다' },
      { es: 'tomar fotos', ko: '사진을 찍다' },
      { es: 'meterse en el agua', ko: '물에 들어가다' },
      { es: 'protegerse', ko: '자신을 보호하다' },
      { es: 'secarse', ko: '몸을 말리다' },
      { es: 'la sombrilla', ko: '파라솔' },
      { es: 'el protector solar', ko: '선크림' },
    ],
  },
  {
    id: 'day13', emoji: '🛒',
    title: 'Day 13 · 마트',
    subtitle: '¿Qué hago en el supermercado?',
    cards: [
      { es: 'el supermercado', ko: '슈퍼마켓' },
      { es: 'el carrito', ko: '카트' },
      { es: 'la lista de compras', ko: '쇼핑 리스트' },
      { es: 'el pasillo', ko: '진열대 통로' },
      { es: 'la caja', ko: '계산대' },
      { es: 'comprar', ko: '사다' },
      { es: 'pagar', ko: '결제하다' },
      { es: 'devolver', ko: '반품하다' },
      { es: 'la oferta', ko: '할인, 행사' },
      { es: 'la bolsa', ko: '봉투' },
      { es: 'el recibo', ko: '영수증' },
      { es: 'hacer la compra', ko: '장을 보다' },
    ],
  },
  {
    id: 'day14', emoji: '🏥',
    title: 'Day 14 · 병원',
    subtitle: '¿Qué hago en el hospital?',
    cards: [
      { es: 'el hospital', ko: '병원' },
      { es: 'el médico', ko: '의사' },
      { es: 'la enfermera', ko: '간호사' },
      { es: 'el síntoma', ko: '증상' },
      { es: 'la receta', ko: '처방전' },
      { es: 'la cita', ko: '예약, 진료 약속' },
      { es: 'estar enfermo', ko: '아프다' },
      { es: 'tomar la temperatura', ko: '체온을 재다' },
      { es: 'examinar', ko: '진찰하다' },
      { es: 'recetar', ko: '처방하다' },
      { es: 'la sala de espera', ko: '대기실' },
      { es: 'pedir cita', ko: '진료 예약을 하다' },
    ],
  },
  {
    id: 'day15', emoji: '☕',
    title: 'Day 15 · 주말',
    subtitle: '¿Qué hago el fin de semana?',
    cards: [
      { es: 'el fin de semana', ko: '주말' },
      { es: 'la cafetería', ko: '카페' },
      { es: 'el parque', ko: '공원' },
      { es: 'descansar', ko: '쉬다' },
      { es: 'quedar con amigos', ko: '친구와 만나기로 하다' },
      { es: 'tomar un café', ko: '커피 한 잔 마시다' },
      { es: 'dar un paseo', ko: '산책하다' },
      { es: 'ver una película', ko: '영화를 보다' },
      { es: 'salir a cenar', ko: '저녁 먹으러 나가다' },
      { es: 'pasar tiempo en casa', ko: '집에서 시간을 보내다' },
      { es: 'dormir hasta tarde', ko: '늦잠을 자다' },
      { es: 'hacer las tareas del hogar', ko: '집안일을 하다' },
    ],
  },
  {
    id: 'day16', emoji: '👨‍👩‍👧',
    title: 'Day 16 · 가족',
    subtitle: '¿Quiénes son mi familia?',
    cards: [
      { es: 'el padre', ko: '아버지' },
      { es: 'la madre', ko: '어머니' },
      { es: 'el hermano', ko: '남자 형제' },
      { es: 'la hermana', ko: '여자 형제' },
      { es: 'el hijo', ko: '아들' },
      { es: 'la hija', ko: '딸' },
      { es: 'el novio', ko: '남자친구' },
      { es: 'la novia', ko: '여자친구' },
      { es: 'el amigo', ko: '친구 (남)' },
      { es: 'la pareja', ko: '연인, 파트너' },
      { es: 'el abuelo', ko: '할아버지' },
      { es: 'la abuela', ko: '할머니' },
    ],
  },
  {
    id: 'day17', emoji: '🤗',
    title: 'Day 17 · 누구랑?',
    subtitle: '¿Con quién estoy?',
    cards: [
      { es: 'Estoy con mi familia.', ko: '나는 가족과 함께 있다.' },
      { es: 'Estoy con mis amigos.', ko: '나는 친구들과 함께 있다.' },
      { es: 'Estoy con mi pareja.', ko: '나는 연인과 함께 있다.' },
      { es: 'Estoy solo.', ko: '나는 혼자이다. (남)' },
      { es: 'Estoy sola.', ko: '나는 혼자이다. (여)' },
      { es: 'Voy con mi hermano.', ko: '나는 형/오빠와 함께 간다.' },
      { es: 'Hablo con mi madre.', ko: '나는 어머니와 이야기한다.' },
      { es: 'Vivo con mis padres.', ko: '나는 부모님과 산다.' },
      { es: 'Trabajo con mi jefe.', ko: '나는 상사와 일한다.' },
      { es: 'Salgo con mis amigos.', ko: '나는 친구들과 외출한다.' },
      { es: 'Estudio con mi compañero.', ko: '나는 동료와 공부한다.' },
      { es: 'Como con mi familia.', ko: '나는 가족과 함께 식사한다.' },
    ],
  },
  {
    id: 'day18', emoji: '🌴',
    title: 'Day 18 · 휴가',
    subtitle: '¿Qué hago en las vacaciones?',
    cards: [
      { es: 'las vacaciones', ko: '휴가, 방학' },
      { es: 'el extranjero', ko: '해외' },
      { es: 'el senderismo', ko: '하이킹, 등산' },
      { es: 'viajar al extranjero', ko: '해외여행을 가다' },
      { es: 'visitar una ciudad', ko: '도시를 방문하다' },
      { es: 'sacar fotos', ko: '사진을 찍다' },
      { es: 'descansar en la playa', ko: '해변에서 쉬다' },
      { es: 'hacer senderismo', ko: '하이킹하다' },
      { es: 'relajarse', ko: '휴식을 취하다' },
      { es: 'quedarse en casa', ko: '집에 머무르다' },
      { es: 'reservar un hotel', ko: '호텔을 예약하다' },
      { es: 'hacer turismo', ko: '관광하다' },
    ],
  },
  {
    id: 'day19', emoji: '🏦',
    title: 'Day 19 · 은행',
    subtitle: '¿Qué hago en el banco?',
    cards: [
      { es: 'el banco', ko: '은행' },
      { es: 'la cuenta', ko: '계좌' },
      { es: 'el cajero automático', ko: 'ATM' },
      { es: 'la tarjeta', ko: '카드' },
      { es: 'el dinero', ko: '돈' },
      { es: 'depositar', ko: '입금하다' },
      { es: 'retirar', ko: '출금하다' },
      { es: 'cambiar dinero', ko: '환전하다' },
      { es: 'transferir', ko: '송금하다' },
      { es: 'abrir una cuenta', ko: '계좌를 개설하다' },
      { es: 'la comisión', ko: '수수료' },
      { es: 'consultar el saldo', ko: '잔액을 조회하다' },
    ],
  },
  {
    id: 'day20', emoji: '🎬',
    title: 'Day 20 · 영화관',
    subtitle: '¿Qué hago en el cine?',
    cards: [
      { es: 'el cine', ko: '영화관' },
      { es: 'la entrada', ko: '티켓' },
      { es: 'la pantalla', ko: '스크린' },
      { es: 'las palomitas', ko: '팝콘' },
      { es: 'la bebida', ko: '음료' },
      { es: 'el asiento', ko: '좌석' },
      { es: 'comprar una entrada', ko: '티켓을 사다' },
      { es: 'reservar una entrada', ko: '티켓을 예매하다' },
      { es: 'ver una película', ko: '영화를 보다' },
      { es: 'sentarse en el asiento', ko: '좌석에 앉다' },
      { es: 'salir del cine', ko: '영화관에서 나오다' },
    ],
  },
  {
    id: 'day21', emoji: '👗',
    title: 'Day 21 · 옷가게',
    subtitle: '¿Qué hago en la tienda de ropa?',
    cards: [
      { es: 'la ropa', ko: '옷' },
      { es: 'la talla', ko: '사이즈' },
      { es: 'el probador', ko: '탈의실' },
      { es: 'el espejo', ko: '거울' },
      { es: 'el dependiente', ko: '직원 (남)' },
      { es: 'probarse la ropa', ko: '옷을 입어보다' },
      { es: 'pagar con tarjeta', ko: '카드로 결제하다' },
      { es: 'pagar en efectivo', ko: '현금으로 결제하다' },
      { es: 'Me queda bien.', ko: '잘 맞아요.' },
      { es: 'Me queda grande.', ko: '사이즈가 커요.' },
      { es: '¿Qué talla usas?', ko: '무슨 사이즈 입으세요?' },
      { es: 'Solo estoy mirando.', ko: '그냥 구경 중이에요.' },
    ],
  },
  {
    id: 'day22', emoji: '💊',
    title: 'Day 22 · 약국',
    subtitle: '¿Qué hago en la farmacia?',
    cards: [
      { es: 'la farmacia', ko: '약국' },
      { es: 'el medicamento', ko: '약' },
      { es: 'la pastilla', ko: '알약' },
      { es: 'el jarabe', ko: '시럽 (물약)' },
      { es: 'la pomada', ko: '연고' },
      { es: 'la tirita', ko: '일회용 밴드' },
      { es: 'el dolor de cabeza', ko: '두통' },
      { es: 'el dolor de garganta', ko: '인후통' },
      { es: 'la tos', ko: '기침' },
      { es: 'la fiebre', ko: '열' },
      { es: 'Tengo dolor de cabeza.', ko: '나는 머리가 아파요.' },
      { es: '¿Tiene algo para la tos?', ko: '기침에 듣는 약 있나요?' },
    ],
  },
  {
    id: 'day23', emoji: '🏨',
    title: 'Day 23 · 호텔',
    subtitle: '¿Qué hago en el hotel?',
    cards: [
      { es: 'el hotel', ko: '호텔' },
      { es: 'la recepción', ko: '리셉션' },
      { es: 'la habitación', ko: '객실' },
      { es: 'la reserva', ko: '예약' },
      { es: 'la llave', ko: '열쇠, 카드키' },
      { es: 'el desayuno', ko: '조식' },
      { es: 'hacer el check-in', ko: '체크인하다' },
      { es: 'hacer el check-out', ko: '체크아웃하다' },
      { es: 'dejar el equipaje', ko: '짐을 맡기다' },
      { es: 'No funciona.', ko: '작동이 안돼요.' },
      { es: 'Quisiera otra habitación.', ko: '다른 객실을 원합니다.' },
    ],
  },
  {
    id: 'day24', emoji: '🥩',
    title: 'Day 24 · 정육점',
    subtitle: '¿Qué hago en la carnicería?',
    cards: [
      { es: 'la carne de res', ko: '소고기' },
      { es: 'la carne de cerdo', ko: '돼지고기' },
      { es: 'el pollo', ko: '닭고기' },
      { es: 'la pechuga', ko: '닭가슴살' },
      { es: 'el muslo', ko: '닭 허벅지' },
      { es: 'las costillas', ko: '갈비' },
      { es: 'la carne picada', ko: '다진 고기' },
      { es: 'tierna', ko: '연한' },
      { es: 'dura', ko: '질긴' },
      { es: 'un kilo de carne', ko: '고기 1kg' },
      { es: 'medio kilo', ko: '500g, 반 킬로' },
      { es: 'Deme pechuga de pollo.', ko: '닭가슴살 주세요.' },
    ],
  },
  {
    id: 'day25', emoji: '👠',
    title: 'Day 25 · 신발가게',
    subtitle: '¿Qué hago en la zapatería?',
    cards: [
      { es: 'los zapatos', ko: '구두' },
      { es: 'los tenis', ko: '운동화' },
      { es: 'las sandalias', ko: '샌들' },
      { es: 'las botas', ko: '부츠' },
      { es: 'las bailarinas', ko: '플랫슈즈' },
      { es: 'el tacón', ko: '굽' },
      { es: 'el tacón alto', ko: '하이힐, 높은 굽' },
      { es: 'zapatos planos', ko: '굽이 없는 신발' },
      { es: 'el número', ko: '사이즈 (신발)' },
      { es: 'probarse los zapatos', ko: '신발을 신어보다' },
      { es: 'Me quedan bien.', ko: '잘 맞아요.' },
      { es: 'Me quedan grandes.', ko: '사이즈가 커요.' },
      { es: 'Son cómodos.', ko: '편해요.' },
      { es: '¿Qué número usa?', ko: '사이즈가 어떻게 되세요?' },
      { es: 'Busco zapatos de tacón medio.', ko: '중간 굽 신발을 찾고 있어요.' },
    ],
  },
  {
    id: 'day26', emoji: '💍',
    title: 'Day 26 · 보석점',
    subtitle: '¿Qué hago en la joyería?',
    cards: [
      { es: 'la joya', ko: '보석' },
      { es: 'el anillo', ko: '반지' },
      { es: 'el collar', ko: '목걸이' },
      { es: 'los pendientes', ko: '귀걸이 (항상 복수)' },
      { es: 'la pulsera', ko: '팔찌' },
      { es: 'el oro', ko: '금' },
      { es: 'la plata', ko: '은' },
      { es: 'el diamante', ko: '다이아몬드' },
      { es: 'el regalo', ko: '선물' },
      { es: 'un anillo de oro', ko: '금반지' },
      { es: 'regalar joyas', ko: '보석을 선물하다' },
      { es: 'Le voy a regalar joyas.', ko: '그(녀)에게 보석을 선물할 것이다.' },
      { es: 'Me gustan los pendientes con diamantes.', ko: '다이아 박힌 귀걸이를 좋아한다.' },
    ],
  },
  {
    id: 'day27', emoji: '🎬',
    title: 'Day 27 · 영화 장르',
    subtitle: '¿Qué tipo de película te gusta?',
    cards: [
      { es: 'películas de acción', ko: '액션 영화' },
      { es: 'películas de comedia', ko: '코미디 영화' },
      { es: 'películas románticas', ko: '로맨스 영화' },
      { es: 'películas de terror', ko: '공포 영화' },
      { es: 'películas de ciencia ficción', ko: 'SF 영화' },
      { es: 'películas de animación', ko: '애니메이션 영화' },
      { es: 'Me gusta la comedia.', ko: '나는 코미디를 좋아한다. (단수)' },
      { es: 'Me gustan las películas de acción.', ko: '나는 액션 영화들을 좋아한다. (복수)' },
      { es: 'porque son emocionantes', ko: '흥미진진해서' },
      { es: 'porque son divertidas', ko: '재미있어서' },
      { es: '¿Te gustan las películas de terror?', ko: '공포 영화 좋아해?' },
      { es: 'No me gustan las películas de terror.', ko: '나는 공포 영화를 좋아하지 않는다.' },
    ],
  },
  {
    id: 'day28', emoji: '🎵',
    title: 'Day 28 · 음악 장르',
    subtitle: '¿Qué tipo de música escuchas?',
    cards: [
      { es: 'el pop', ko: '팝' },
      { es: 'el rock', ko: '락' },
      { es: 'el hip-hop', ko: '힙합' },
      { es: 'la música clásica', ko: '클래식 음악' },
      { es: 'el jazz', ko: '재즈' },
      { es: 'el reggaetón', ko: '레게톤' },
      { es: 'la música electrónica', ko: '전자 음악' },
      { es: 'el K-pop', ko: '케이팝' },
      { es: 'Escucho música.', ko: '나는 음악을 듣는다.' },
      { es: 'Me encanta la música clásica.', ko: '나는 클래식 음악을 정말 좋아한다.' },
      { es: 'Me encantan las comedias.', ko: '나는 코미디를 정말 좋아한다. (복수)' },
      { es: 'Escucho jazz cuando estudio.', ko: '공부할 때 재즈를 듣는다.' },
      { es: 'Escucho música cuando trabajo.', ko: '일할 때 음악을 듣는다.' },
    ],
  },
  {
    id: 'day29', emoji: '😋',
    title: 'Day 29 · 맛/풍미',
    subtitle: '¿Qué sabor tiene?',
    cards: [
      { es: 'dulce', ko: '달콤한' },
      { es: 'salado', ko: '짠' },
      { es: 'ácido', ko: '신' },
      { es: 'amargo', ko: '쓴' },
      { es: 'picante', ko: '매운' },
      { es: 'fresco', ko: '신선한, 상쾌한' },
      { es: 'ligero', ko: '가벼운, 부담없는' },
      { es: 'suave', ko: '부드러운' },
      { es: 'crujiente', ko: '바삭한' },
      { es: 'rico', ko: '맛있다' },
      { es: 'riquísimo', ko: '정말 맛있다 (최상급)' },
      { es: 'delicioso', ko: '맛있다 (격식)' },
      { es: 'exquisito', ko: '풍미가 훌륭한' },
      { es: 'Está delicioso.', ko: '맛있어요. (지금)' },
      { es: 'El chocolate es muy dulce.', ko: '초콜릿은 매우 달다. (본질)' },
    ],
  },
  {
    id: 'day30', emoji: '💪',
    title: 'Day 30 · 건강 관리',
    subtitle: '¿Qué hago para mi salud?',
    cards: [
      { es: 'la salud', ko: '건강' },
      { es: 'sano', ko: '건강한 (남)' },
      { es: 'la comida rápida', ko: '패스트푸드' },
      { es: 'la rutina', ko: '루틴' },
      { es: 'hacer ejercicio', ko: '운동하다' },
      { es: 'ir al gimnasio', ko: '헬스장에 가다' },
      { es: 'hacer yoga', ko: '요가하다' },
      { es: 'comer sano', ko: '건강하게 먹다' },
      { es: 'beber mucha agua', ko: '물을 많이 마시다' },
      { es: 'evitar comida rápida', ko: '패스트푸드를 피하다' },
      { es: 'dormir bien', ko: '잘 자다' },
      { es: 'cuidarse', ko: '자기 건강을 챙기다' },
      { es: 'para mi salud', ko: '나의 건강을 위해' },
      { es: 'Me cuido mucho.', ko: '나는 건강을 많이 챙긴다.' },
    ],
  },
  {
    id: 'day31', emoji: '😴',
    title: 'Day 31 · 자기 전 루틴',
    subtitle: '¿Qué hago antes de dormir?',
    cards: [
      { es: 'la cara', ko: '얼굴' },
      { es: 'los dientes', ko: '치아' },
      { es: 'el pijama', ko: '잠옷' },
      { es: 'lavarse la cara', ko: '세수하다' },
      { es: 'cepillarse los dientes', ko: '양치하다' },
      { es: 'ducharse', ko: '샤워하다' },
      { es: 'ponerse el pijama', ko: '잠옷을 입다' },
      { es: 'acostarse', ko: '잠자리에 들다' },
      { es: 'dormirse', ko: '잠들어 버리다' },
      { es: 'usar el móvil', ko: '휴대폰을 사용하다' },
      { es: 'ver videos', ko: '영상을 보다' },
      { es: 'antes de dormir', ko: '자기 전에' },
      { es: 'Me lavo la cara antes de dormir.', ko: '나는 자기 전에 세수한다.' },
      { es: 'Siempre me ducho antes de dormir.', ko: '나는 항상 자기 전에 샤워한다.' },
    ],
  },
  {
    id: 'day32', emoji: '🍔',
    title: 'Day 32 · 배고플 때',
    subtitle: '¿Qué compro cuando tengo hambre?',
    cards: [
      { es: 'una hamburguesa', ko: '햄버거' },
      { es: 'las patatas fritas', ko: '감자튀김' },
      { es: 'el pollo frito', ko: '치킨' },
      { es: 'una pizza', ko: '피자' },
      { es: 'un sándwich', ko: '샌드위치' },
      { es: 'un perrito caliente', ko: '핫도그' },
      { es: 'una ensalada', ko: '샐러드' },
      { es: 'un croissant', ko: '크로아상' },
      { es: 'el pan', ko: '빵' },
      { es: 'un pastel', ko: '케이크' },
      { es: 'ramen', ko: '라면' },
      { es: 'Tengo hambre.', ko: '나는 배고프다.' },
      { es: 'Tengo sed.', ko: '나는 목마르다.' },
      { es: 'Tengo sueño.', ko: '나는 졸리다.' },
      { es: 'saltarse el desayuno', ko: '아침을 거르다' },
      { es: 'Cuando tengo hambre, compro pizza.', ko: '배고플 때 피자를 산다.' },
    ],
  },
 {
    id: 'day33', emoji: '🎨',
    title: 'Day 33 · 취미',
    subtitle: '¿Cuál es mi pasatiempo favorito?',
    cards: [
      { es: 'el pasatiempo', ko: '취미' },
      { es: 'la música', ko: '음악' },
      { es: 'los libros', ko: '책 (복수)' },
      { es: 'los deportes', ko: '운동, 스포츠' },
      { es: 'los videojuegos', ko: '비디오 게임' },
      { es: 'escuchar música', ko: '음악을 듣다' },
      { es: 'ver películas', ko: '영화를 보다' },
      { es: 'leer libros', ko: '책을 읽다' },
      { es: 'viajar', ko: '여행하다' },
      { es: 'cocinar', ko: '요리하다' },
      { es: 'bailar', ko: '춤추다' },
      { es: 'hacer ejercicio', ko: '운동하다' },
      { es: 'jugar videojuegos', ko: '게임을 하다' },
      { es: 'divertido', ko: '재미있는' },
      { es: 'relajante', ko: '편안한, 마음이 차분해지는' },
      { es: 'interesante', ko: '흥미로운' },
      { es: 'emocionante', ko: '신나는, 흥분되는' },
      { es: 'Mi pasatiempo favorito es escuchar música.', ko: '내가 가장 좋아하는 취미는 음악 듣기이다.' },
      { es: 'Mi pasatiempo favorito es viajar.', ko: '내가 가장 좋아하는 취미는 여행이다.' },
      { es: 'Mi pasatiempo favorito es cocinar.', ko: '내가 가장 좋아하는 취미는 요리이다.' },
      { es: 'Mi pasatiempo favorito es leer libros.', ko: '내가 가장 좋아하는 취미는 독서이다.' },
      { es: 'Mi pasatiempo favorito es viajar porque es divertido.', ko: '내가 가장 좋아하는 취미는 여행인데, 재미있기 때문이다.' },
      { es: 'Mi pasatiempo favorito es cocinar porque es relajante.', ko: '내가 가장 좋아하는 취미는 요리인데, 편안하기 때문이다.' },
      { es: '¿Cuál es tu pasatiempo favorito?', ko: '너의 취미는 무엇이야?' },
    ],
  },
];

/* 새 Day 추가 예시 (복붙해서 사용하세요)
  {
    id: 'day33', emoji: '🎉',
    title: 'Day 33 · 새 주제',
    subtitle: '¿Qué hago ...?',
    cards: [
      { es: 'la palabra', ko: '단어' },
      { es: 'la expresión', ko: '표현' },
    ],
  },
*/
